# Dependency Review
# is only supported on pull_request events.
---
name: Pull Request

# "This run was triggered by the "push" event, which is unsupported.
#  Please ensure you are using the "pull_request" event for this workflow."
on:
  pull_request:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  audit:
    name: Audit
    uses: percebus/github-actions-npm/.github/workflows/dependency-review.yml@main
    permissions:
      contents: read
      pull-requests: read
